# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Lint with flake8
          run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: SCP Command to Transfer Files
          # You may pin to the exact commit or the version.
          # uses: appleboy/scp-action@edc8ec9139a2687bcebf0249d0352ff2a988df00
          uses: appleboy/scp-action@v0.1.1
          with:
            # scp remote host
            host: andrewbounds.com # optional
            # scp remote port
            #port: # optional, default is 22
            # scp username
            username: ${{ secrets.SSH_USER }} # optional
            # content of ssh private key. ex raw content of ~/.ssh/id_rsa
            key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
            # path of ssh private key
            #key_path: # optional
            # ssh key passphrase
            passphrase: ${{ secrets.SSH_KEY_PASS }} # optional
            # target path on the server
            target: /var/www/andrewbounds # optional
            # scp file list
            #source: # optional
